import { createRouter, createWebHistory, type RouteRecordRaw } from 'vue-router'


const routes: RouteRecordRaw[] = [
  { path: '/', redirect: '/index/home' },
  {
    path: '/index',
    component: () => import('@/views/Index.vue'),
    children: [
      { path: 'home', component: () => import('@/views/Home.vue') },
      { path: 'center', component: () => import('@/views/Center.vue') },
      { path: 'user', component: () => import('@/views/modules/user/List.vue') },
      { path: 'userAdd', component: () => import('@/views/modules/user/AddOrUpdate.vue'), meta: { activeMenu: '/index/user' } },
      { path: 'userDetail', component: () => import('@/views/modules/user/Detail.vue'), meta: { activeMenu: '/index/user' } },
      { path: 'coach', component: () => import('@/views/modules/coach/List.vue') },
      { path: 'coachAdd', component: () => import('@/views/modules/coach/AddOrUpdate.vue'), meta: { activeMenu: '/index/coach' } },
      { path: 'coachDetail', component: () => import('@/views/modules/coach/Detail.vue'), meta: { activeMenu: '/index/coach' } },
      { path: 'coachmember', component: () => import('@/views/modules/coachmember/List.vue') },
      { path: 'coachmemberAdd', component: () => import('@/views/modules/coachmember/AddOrUpdate.vue'), meta: { activeMenu: '/index/coachmember' } },
      { path: 'coachmemberDetail', component: () => import('@/views/modules/coachmember/Detail.vue'), meta: { activeMenu: '/index/coachmember' } },
      { path: 'trainingplan', component: () => import('@/views/modules/trainingplan/List.vue') },
      { path: 'trainingplanAdd', component: () => import('@/views/modules/trainingplan/AddOrUpdate.vue'), meta: { activeMenu: '/index/trainingplan' } },
      { path: 'trainingplanDetail', component: () => import('@/views/modules/trainingplan/Detail.vue'), meta: { activeMenu: '/index/trainingplan' } },
      { path: 'trainingplanitem', component: () => import('@/views/modules/trainingplanitem/List.vue') },
      { path: 'trainingplanitemAdd', component: () => import('@/views/modules/trainingplanitem/AddOrUpdate.vue'), meta: { activeMenu: '/index/trainingplanitem' } },
      { path: 'trainingplanitemDetail', component: () => import('@/views/modules/trainingplanitem/Detail.vue'), meta: { activeMenu: '/index/trainingplanitem' } },
      { path: 'trainingrecord', component: () => import('@/views/modules/trainingrecord/List.vue') },
      { path: 'trainingrecordAdd', component: () => import('@/views/modules/trainingrecord/AddOrUpdate.vue'), meta: { activeMenu: '/index/trainingrecord' } },
      { path: 'trainingrecordDetail', component: () => import('@/views/modules/trainingrecord/Detail.vue'), meta: { activeMenu: '/index/trainingrecord' } },
      { path: 'coachreview', component: () => import('@/views/modules/coachreview/List.vue') },
      { path: 'coachreviewAdd', component: () => import('@/views/modules/coachreview/AddOrUpdate.vue'), meta: { activeMenu: '/index/coachreview' } },
      { path: 'coachreviewDetail', component: () => import('@/views/modules/coachreview/Detail.vue'), meta: { activeMenu: '/index/coachreview' } },
      { path: 'coursetype', component: () => import('@/views/modules/coursetype/List.vue') },
      { path: 'coursetypeAdd', component: () => import('@/views/modules/coursetype/AddOrUpdate.vue'), meta: { activeMenu: '/index/coursetype' } },
      { path: 'coursetypeDetail', component: () => import('@/views/modules/coursetype/Detail.vue'), meta: { activeMenu: '/index/coursetype' } },
      { path: 'course', component: () => import('@/views/modules/course/List.vue') },
      { path: 'courseAdd', component: () => import('@/views/modules/course/AddOrUpdate.vue'), meta: { activeMenu: '/index/course' } },
      { path: 'courseDetail', component: () => import('@/views/modules/course/Detail.vue'), meta: { activeMenu: '/index/course' } },
      { path: 'courseenrollment', component: () => import('@/views/modules/courseenrollment/List.vue') },
      { path: 'courseenrollmentAdd', component: () => import('@/views/modules/courseenrollment/AddOrUpdate.vue'), meta: { activeMenu: '/index/courseenrollment' } },
      { path: 'courseenrollmentDetail', component: () => import('@/views/modules/courseenrollment/Detail.vue'), meta: { activeMenu: '/index/courseenrollment' } },
      { path: 'producttype', component: () => import('@/views/modules/producttype/List.vue') },
      { path: 'producttypeAdd', component: () => import('@/views/modules/producttype/AddOrUpdate.vue'), meta: { activeMenu: '/index/producttype' } },
      { path: 'producttypeDetail', component: () => import('@/views/modules/producttype/Detail.vue'), meta: { activeMenu: '/index/producttype' } },
      { path: 'product', component: () => import('@/views/modules/product/List.vue') },
      { path: 'productAdd', component: () => import('@/views/modules/product/AddOrUpdate.vue'), meta: { activeMenu: '/index/product' } },
      { path: 'productDetail', component: () => import('@/views/modules/product/Detail.vue'), meta: { activeMenu: '/index/product' } },
      { path: 'productorder', component: () => import('@/views/modules/productorder/List.vue') },
      { path: 'productorderAdd', component: () => import('@/views/modules/productorder/AddOrUpdate.vue'), meta: { activeMenu: '/index/productorder' } },
      { path: 'productorderDetail', component: () => import('@/views/modules/productorder/Detail.vue'), meta: { activeMenu: '/index/productorder' } },
      { path: 'membershippackage', component: () => import('@/views/modules/membershippackage/List.vue') },
      { path: 'membershippackageAdd', component: () => import('@/views/modules/membershippackage/AddOrUpdate.vue'), meta: { activeMenu: '/index/membershippackage' } },
      { path: 'membershippackageDetail', component: () => import('@/views/modules/membershippackage/Detail.vue'), meta: { activeMenu: '/index/membershippackage' } },
      { path: 'cardapplication', component: () => import('@/views/modules/cardapplication/List.vue') },
      { path: 'cardapplicationAdd', component: () => import('@/views/modules/cardapplication/AddOrUpdate.vue'), meta: { activeMenu: '/index/cardapplication' } },
      { path: 'cardapplicationDetail', component: () => import('@/views/modules/cardapplication/Detail.vue'), meta: { activeMenu: '/index/cardapplication' } },
      { path: 'cardrenewal', component: () => import('@/views/modules/cardrenewal/List.vue') },
      { path: 'cardrenewalAdd', component: () => import('@/views/modules/cardrenewal/AddOrUpdate.vue'), meta: { activeMenu: '/index/cardrenewal' } },
      { path: 'cardrenewalDetail', component: () => import('@/views/modules/cardrenewal/Detail.vue'), meta: { activeMenu: '/index/cardrenewal' } },
      { path: 'sharetype', component: () => import('@/views/modules/sharetype/List.vue') },
      { path: 'sharetypeAdd', component: () => import('@/views/modules/sharetype/AddOrUpdate.vue'), meta: { activeMenu: '/index/sharetype' } },
      { path: 'sharetypeDetail', component: () => import('@/views/modules/sharetype/Detail.vue'), meta: { activeMenu: '/index/sharetype' } },
      { path: 'share', component: () => import('@/views/modules/share/List.vue') },
      { path: 'shareAdd', component: () => import('@/views/modules/share/AddOrUpdate.vue'), meta: { activeMenu: '/index/share' } },
      { path: 'shareDetail', component: () => import('@/views/modules/share/Detail.vue'), meta: { activeMenu: '/index/share' } },
      { path: 'feedback', component: () => import('@/views/modules/feedback/List.vue') },
      { path: 'feedbackAdd', component: () => import('@/views/modules/feedback/AddOrUpdate.vue'), meta: { activeMenu: '/index/feedback' } },
      { path: 'feedbackDetail', component: () => import('@/views/modules/feedback/Detail.vue'), meta: { activeMenu: '/index/feedback' } },
      { path: 'discusscourse', component: () => import('@/views/modules/discusscourse/List.vue') },
      { path: 'discusscourseAdd', component: () => import('@/views/modules/discusscourse/AddOrUpdate.vue'), meta: { activeMenu: '/index/discusscourse' } },
      { path: 'discusscourseDetail', component: () => import('@/views/modules/discusscourse/Detail.vue'), meta: { activeMenu: '/index/discusscourse' } },
      { path: 'cancelcourseenrollment', component: () => import('@/views/modules/cancelcourseenrollment/List.vue') },
      { path: 'cancelcourseenrollmentAdd', component: () => import('@/views/modules/cancelcourseenrollment/AddOrUpdate.vue'), meta: { activeMenu: '/index/cancelcourseenrollment' } },
      { path: 'cancelcourseenrollmentDetail', component: () => import('@/views/modules/cancelcourseenrollment/Detail.vue'), meta: { activeMenu: '/index/cancelcourseenrollment' } },
      { path: 'refundcourseenrollment', component: () => import('@/views/modules/refundcourseenrollment/List.vue') },
      { path: 'refundcourseenrollmentAdd', component: () => import('@/views/modules/refundcourseenrollment/AddOrUpdate.vue'), meta: { activeMenu: '/index/refundcourseenrollment' } },
      { path: 'refundcourseenrollmentDetail', component: () => import('@/views/modules/refundcourseenrollment/Detail.vue'), meta: { activeMenu: '/index/refundcourseenrollment' } },
      { path: 'discussproduct', component: () => import('@/views/modules/discussproduct/List.vue') },
      { path: 'discussproductAdd', component: () => import('@/views/modules/discussproduct/AddOrUpdate.vue'), meta: { activeMenu: '/index/discussproduct' } },
      { path: 'discussproductDetail', component: () => import('@/views/modules/discussproduct/Detail.vue'), meta: { activeMenu: '/index/discussproduct' } },
      { path: 'cancelcardapplication', component: () => import('@/views/modules/cancelcardapplication/List.vue') },
      { path: 'cancelcardapplicationAdd', component: () => import('@/views/modules/cancelcardapplication/AddOrUpdate.vue'), meta: { activeMenu: '/index/cancelcardapplication' } },
      { path: 'cancelcardapplicationDetail', component: () => import('@/views/modules/cancelcardapplication/Detail.vue'), meta: { activeMenu: '/index/cancelcardapplication' } },
      { path: 'refundcardapplication', component: () => import('@/views/modules/refundcardapplication/List.vue') },
      { path: 'refundcardapplicationAdd', component: () => import('@/views/modules/refundcardapplication/AddOrUpdate.vue'), meta: { activeMenu: '/index/refundcardapplication' } },
      { path: 'refundcardapplicationDetail', component: () => import('@/views/modules/refundcardapplication/Detail.vue'), meta: { activeMenu: '/index/refundcardapplication' } },
      { path: 'cancelproductorder', component: () => import('@/views/modules/cancelproductorder/List.vue') },
      { path: 'cancelproductorderAdd', component: () => import('@/views/modules/cancelproductorder/AddOrUpdate.vue'), meta: { activeMenu: '/index/cancelproductorder' } },
      { path: 'cancelproductorderDetail', component: () => import('@/views/modules/cancelproductorder/Detail.vue'), meta: { activeMenu: '/index/cancelproductorder' } },
      { path: 'refundproductorder', component: () => import('@/views/modules/refundproductorder/List.vue') },
      { path: 'refundproductorderAdd', component: () => import('@/views/modules/refundproductorder/AddOrUpdate.vue'), meta: { activeMenu: '/index/refundproductorder' } },
      { path: 'refundproductorderDetail', component: () => import('@/views/modules/refundproductorder/Detail.vue'), meta: { activeMenu: '/index/refundproductorder' } },
      { path: 'discussproductorder', component: () => import('@/views/modules/discussproductorder/List.vue') },
      { path: 'discussproductorderAdd', component: () => import('@/views/modules/discussproductorder/AddOrUpdate.vue'), meta: { activeMenu: '/index/discussproductorder' } },
      { path: 'discussproductorderDetail', component: () => import('@/views/modules/discussproductorder/Detail.vue'), meta: { activeMenu: '/index/discussproductorder' } },
      { path: 'cancelcardrenewal', component: () => import('@/views/modules/cancelcardrenewal/List.vue') },
      { path: 'cancelcardrenewalAdd', component: () => import('@/views/modules/cancelcardrenewal/AddOrUpdate.vue'), meta: { activeMenu: '/index/cancelcardrenewal' } },
      { path: 'cancelcardrenewalDetail', component: () => import('@/views/modules/cancelcardrenewal/Detail.vue'), meta: { activeMenu: '/index/cancelcardrenewal' } },
      { path: 'refundcardrenewal', component: () => import('@/views/modules/refundcardrenewal/List.vue') },
      { path: 'refundcardrenewalAdd', component: () => import('@/views/modules/refundcardrenewal/AddOrUpdate.vue'), meta: { activeMenu: '/index/refundcardrenewal' } },
      { path: 'refundcardrenewalDetail', component: () => import('@/views/modules/refundcardrenewal/Detail.vue'), meta: { activeMenu: '/index/refundcardrenewal' } },
      { path: 'discussshare', component: () => import('@/views/modules/discussshare/List.vue') },
      { path: 'discussshareAdd', component: () => import('@/views/modules/discussshare/AddOrUpdate.vue'), meta: { activeMenu: '/index/discussshare' } },
      { path: 'discussshareDetail', component: () => import('@/views/modules/discussshare/Detail.vue'), meta: { activeMenu: '/index/discussshare' } },
      { path: 'discussnews', component: () => import('@/views/modules/discussnews/List.vue') },
      { path: 'discussnewsAdd', component: () => import('@/views/modules/discussnews/AddOrUpdate.vue'), meta: { activeMenu: '/index/discussnews' } },
      { path: 'discussnewsDetail', component: () => import('@/views/modules/discussnews/Detail.vue'), meta: { activeMenu: '/index/discussnews' } },
      { path: 'newstype', component: () => import('@/views/modules/newstype/List.vue') },
      { path: 'newstypeAdd', component: () => import('@/views/modules/newstype/AddOrUpdate.vue'), meta: { activeMenu: '/index/newstype' } },
      { path: 'newstypeDetail', component: () => import('@/views/modules/newstype/Detail.vue'), meta: { activeMenu: '/index/newstype' } },
      { path: 'news', component: () => import('@/views/modules/news/List.vue') },
      { path: 'newsAdd', component: () => import('@/views/modules/news/AddOrUpdate.vue'), meta: { activeMenu: '/index/news' } },
      { path: 'newsDetail', component: () => import('@/views/modules/news/Detail.vue'), meta: { activeMenu: '/index/news' } },
      { path: 'config', component: () => import('@/views/modules/config/List.vue') },
      { path: 'configAdd', component: () => import('@/views/modules/config/AddOrUpdate.vue'), meta: { activeMenu: '/index/config' } },
      { path: 'configDetail', component: () => import('@/views/modules/config/Detail.vue'), meta: { activeMenu: '/index/config' } },
      { path: 'log', component: () => import('@/views/modules/log/List.vue') },
      { path: 'logAdd', component: () => import('@/views/modules/log/AddOrUpdate.vue'), meta: { activeMenu: '/index/log' } },
      { path: 'logDetail', component: () => import('@/views/modules/log/Detail.vue'), meta: { activeMenu: '/index/log' } },
      { path: 'notify', component: () => import('@/views/modules/notify/List.vue') },
      { path: 'notifyAdd', component: () => import('@/views/modules/notify/AddOrUpdate.vue'), meta: { activeMenu: '/index/notify' } },
      { path: 'notifyDetail', component: () => import('@/views/modules/notify/Detail.vue'), meta: { activeMenu: '/index/notify' } },
      { path: 'chat', component: () => import('@/views/modules/chat/List.vue') },
      { path: 'chatAdd', component: () => import('@/views/modules/chat/AddOrUpdate.vue'), meta: { activeMenu: '/index/chat' } },
      { path: 'chatDetail', component: () => import('@/views/modules/chat/Detail.vue'), meta: { activeMenu: '/index/chat' } },
      { path: 'chatmessage', component: () => import('@/views/modules/chatmessage/List.vue') },
      { path: 'chatmessageAdd', component: () => import('@/views/modules/chatmessage/AddOrUpdate.vue'), meta: { activeMenu: '/index/chatmessage' } },
      { path: 'chatmessageDetail', component: () => import('@/views/modules/chatmessage/Detail.vue'), meta: { activeMenu: '/index/chatmessage' } },
      { path: 'friend', component: () => import('@/views/modules/friend/List.vue') },
      { path: 'friendAdd', component: () => import('@/views/modules/friend/AddOrUpdate.vue'), meta: { activeMenu: '/index/friend' } },
      { path: 'friendDetail', component: () => import('@/views/modules/friend/Detail.vue'), meta: { activeMenu: '/index/friend' } },
      { path: 'notify', component: () => import('@/views/modules/notify/List.vue') },
      { path: 'notifyDetail', component: () => import('@/views/modules/notify/Detail.vue') },
    ]
  }
]

const router = createRouter({
  history: createWebHistory(),
  routes
})

// 不再处理 /login 与 /register 特殊跳转，保持简洁

export default router
